In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_13120\1665395293.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
df = sns.load_dataset("iris")
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
#X is feature vectors
X = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]

# y is labels
Y = df[['species']]

In [4]:
from sklearn.preprocessing import StandardScaler

X_scaled = StandardScaler().fit_transform(X)

In [5]:
# 공분산 matrix

features =X.T  # X 데이터는 150 × 4 이라면,
               # feature 는 4 × 150 이다.

covariance_matrix = np.cov(features)
print(covariance_matrix)

[[ 0.68569351 -0.042434    1.27431544  0.51627069]
 [-0.042434    0.18997942 -0.32965638 -0.12163937]
 [ 1.27431544 -0.32965638  3.11627785  1.2956094 ]
 [ 0.51627069 -0.12163937  1.2956094   0.58100626]]


In [8]:
# 공분산 매트릭스 넣어서 고유값 분해하기
# 아이젠 밸류 큰 것부터 배열해준 것 상위 2개 뽑기(95% 넘어가는 피쳐들 2~3개 선택)
results = values, vectors = np.linalg.eig(covariance_matrix)
# results
print('\nEigenvalues \n%s '% values[:])
print('\nEigenvectros \n%s'  %  vectors[:])


Eigenvalues 
[4.22824171 0.24267075 0.0782095  0.02383509] 

Eigenvectros 
[[ 0.36138659 -0.65658877 -0.58202985  0.31548719]
 [-0.08452251 -0.73016143  0.59791083 -0.3197231 ]
 [ 0.85667061  0.17337266  0.07623608 -0.47983899]
 [ 0.3582892   0.07548102  0.54583143  0.75365743]]
