튜토리얼 개요
이 튜토리얼은 다음과 같이 다섯 부분으로 나뉩니다.

특이값 분해
특이값 분해 계산
SVD에서 행렬 재구성
의사 역에 대한 SVD
차원 축소를 위한 SVD

#### 특이값 분해

In [1]:
# Singular-value decomposition
from numpy import array
from scipy.linalg import svd
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# SVD
U, s, VT = svd(A)
print(U)
print(s)
print(VT)

[[1 2]
 [3 4]
 [5 6]]
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


#### SVD에서 행렬 재구성
원래 행렬은 U, Sigma 및 V^T 요소에서 재구성할 수 있습니다.

svd()에서 반환된 U, s 및 V 요소는 직접 곱할 수 없습니다.

s 벡터는 diag() 함수를 사용하여 대각 행렬로 변환되어야 합니다. 기본적으로 이 함수는 원래 행렬을 기준으로 n x n인 정사각형 행렬을 만듭니다. 이로 인해 행렬의 크기가 행렬의 열 수가 후속 행렬의 행 수와 일치해야 하는 행렬 곱셈 규칙에 맞지 않기 때문에 문제가 발생합니다.

정사각형 시그마 대각선 행렬을 만든 후 행렬의 크기는 다음과 같이 분해하는 원래 m x n 행렬을 기준으로 합니다

In [2]:
# Reconstruct SVD
from numpy import array
from numpy import diag
from numpy import dot
from numpy import zeros
from scipy.linalg import svd
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# Singular-value decomposition
U, s, VT = svd(A)
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[1], :A.shape[1]] = diag(s)
# reconstruct matrix
B = U.dot(Sigma.dot(VT))
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [3]:
# Reconstruct SVD
from numpy import array
from numpy import diag
from numpy import dot
from scipy.linalg import svd
# define a matrix
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
# Singular-value decomposition
U, s, VT = svd(A)
# create n x n Sigma matrix
Sigma = diag(s)
# reconstruct matrix
B = U.dot(Sigma.dot(VT))
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


#### 차원 축소를 위한 SVD
SVD의 인기 있는 응용 분야는 차원 축소입니다.

관측치(행)보다 더 많은 특징(열)과 같이 많은 수의 특징을 갖는 데이터는 예측 문제와 가장 관련이 있는 특징의 더 작은 서브세트로 축소될 수 있습니다.

결과는 원래 행렬에 근사한다고 하는 순위가 낮은 행렬입니다.

이를 위해 원본 데이터에 대해 SVD 연산을 수행하고 시그마에서 상위 k 개의 가장 큰 특이 값을 선택할 수 있습니다. 이러한 열은 Sigma에서 선택하고 V^T에서 선택한 행을 선택할 수 있습니다.

그런 다음 원래 벡터 A의 근사 B를 재구성할 수 있습니다.

In [4]:
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd
# define a matrix
A = array([
 [1,2,3,4,5,6,7,8,9,10],
 [11,12,13,14,15,16,17,18,19,20],
 [21,22,23,24,25,26,27,28,29,30]])
print(A)
# Singular-value decomposition
U, s, VT = svd(A)
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[0], :A.shape[0]] = diag(s)
# select
n_elements = 2
Sigma = Sigma[:, :n_elements]
VT = VT[:n_elements, :]
# reconstruct
B = U.dot(Sigma.dot(VT))
print(B)
# transform
T = U.dot(Sigma)
print(T)
T = A.dot(VT.T)
print(T)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]
